services:
  postgres:
    image: 'postgres:latest'
    container_name: easyup-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-easyup
    restart: always
    ports:
      - "30110:30110"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=30110
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
#      - DATABASE_USER=postgres
#      - DATABASE_PASSWORD=cat8apple10wheel
#      - DATABASE_DB=easyup
      - LINK_LIFITIME=1d
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cat8apple10wheel
      - POSTGRES_DB=easyup
    depends_on:
      - postgres
    networks:
      - app-network
    command: ["sh", "-c", "npm install && npm run build && npm start"]

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge