services:
  db:
    image: postgres:17
    container_name: easyup-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app-3205-team
    ports:
      - "30110:30110"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=30110
      - DATABASE_PORT=3306
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=cat8apple10wheel
      - DATABASE_DB=3205-team
      - LINK_LIFITIME=1d
    depends_on:
      - db
    networks:
      - app-network
    command: ["sh", "-c", "npm install && npm run build && npm start"]

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge